sonar.projectKey=Alex-Farias_prova02-integration-alexnabo
sonar.organization=alex-farias
sonar.projectName=Jest Integration Tests
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8